[bumpver]
current_version = "2022.4.2"
version_pattern = "YYYY.MM.INC1"
commit_message = ":bookmark: bump version {old_version} -> {new_version}"
commit = true
push = false  # diabled for GitHub Actions
tag = true

[bumpver.file_patterns]
"yes_no_words.py" = [
    '__version__ = "{version}"',
]

"version" = [
    'version = "{version}"',
]
