[bumpver]
current_version = "2022.4.3"
version_pattern = "YYYY.MM.INC1"
commit_message = ":bookmark: bump version {old_version} -> {new_version}"
commit = true
push = true  # diabled for GitHub Actions
tag = true

[bumpver.file_patterns]
"yes_no_words.py" = [
    '__version__ = "{version}"',
]

"setup.cfg" = [
    "version = {version}",
]
