name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/actions.yml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/actions.yml"
      - "**.py"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests with Python

    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11-dev"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pytest black

      - name: Format with black
        run: |
          black --check .

      - name: Run tests
        run: |
          pytest .

  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: pipx run build

      - name: Archive files
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
